# -*- coding: utf-8 -*-
"""
FoodSafeML v1.9.0 — 全球全量地区数据模块
==========================================
覆盖 233 个国家/地区 + 国际组织/联盟/论坛。

每个地区元组结构:
  (code, 中文名, 英文名, 本国语言名, 主管机构全称, 适用标准体系, 洲, 体系说明)

适用标准体系(system)取值:
  "GB"      — 中国国标体系(自有)
  "EU"      — 欧盟法规体系(自有)
  "US"      — 美国联邦法规体系(自有)
  "自有"     — 该国独立食品安全法规体系
  "参照EU"  — 参照/采纳欧盟标准
  "参照CODEX"— 参照/采纳Codex标准
  "参照US"  — 参照美国标准
  "国际"     — 国际组织基准

防幻觉原则：主管机构名称力求准确；不确定的小国标注其标准体系归属，
不编造具体机构名(标为"该国食品安全主管机构")。
"""

# (code, zh, en, native, authority_fullname, system, continent, note)
REGIONS_DATA = [
    # ====== 国际基准 / 组织 / 联盟 / 论坛 ======
    ("CODEX", "国际食品法典", "Codex Alimentarius", "Codex Alimentarius",
     "FAO/WHO 食品法典委员会（Codex Alimentarius Commission）", "国际", "国际", "全球食品安全基准标准"),
    ("WHO/JECFA", "世界卫生组织/食品添加剂联合专家委员会", "WHO/FAO JECFA", "JECFA",
     "联合国粮农组织/世界卫生组织 食品添加剂联合专家委员会（JECFA）", "国际", "国际", "食品添加剂风险评估"),
    ("FAO", "联合国粮农组织", "FAO", "FAO",
     "联合国粮食及农业组织（FAO）", "国际", "国际", ""),
    ("WHO", "世界卫生组织", "WHO", "WHO",
     "世界卫生组织（WHO）", "国际", "国际", ""),
    ("ISO", "国际标准化组织", "ISO", "ISO",
     "国际标准化组织（ISO）", "国际", "国际", "食品检测方法标准"),
    ("WTO/SPS", "世贸组织/卫生与植物卫生措施", "WTO/SPS", "WTO/SPS",
     "世界贸易组织 卫生与植物卫生措施委员会（WTO SPS Committee）", "国际", "国际", "SPS协定指定Codex"),
    ("IPCS", "国际化学品安全规划署", "IPCS", "IPCS",
     "WHO 国际化学品安全规划署（IPCS）", "国际", "国际", ""),
    ("IFOAM", "国际有机农业运动联盟", "IFOAM Organics", "IFOAM",
     "国际有机农业运动联盟（IFOAM Organics International）", "国际", "国际", "有机食品标准"),

    # ====== 中国体系 ======
    ("CN", "中国", "China", "中国",
     "中华人民共和国 国家卫生健康委员会 / 国家食品安全风险评估中心（GB 标准）", "GB", "亚洲", ""),
    ("HK", "中国香港", "Hong Kong, China", "香港",
     "中国香港特别行政区政府 食物环境卫生署食物安全中心", "自有", "亚洲", "食安中心规例"),
    ("MO", "中国澳门", "Macao, China", "澳門",
     "中国澳门特别行政区政府 市政署", "自有", "亚洲", ""),
    ("TW", "中国台湾", "Taiwan, China", "臺灣",
     "中国台湾地区 卫生福利部食品药物管理署", "自有", "亚洲", ""),

    # ====== 东亚 ======
    ("JP", "日本", "Japan", "日本",
     "日本国 厚生劳动省（MHLW）", "自有", "亚洲", "食品卫生法/肯定列表制度"),
    ("KR", "韩国", "Republic of Korea", "한국",
     "大韩民国 食品药品安全部（MFDS）", "自有", "亚洲", ""),
    ("KP", "朝鲜", "DPR Korea", "조선",
     "朝鲜民主主义人民共和国 国家科学院", "参照CODEX", "亚洲", ""),
    ("MN", "蒙古", "Mongolia", "Монгол",
     "蒙古国 国家专业监督检查局", "参照CODEX", "亚洲", ""),

    # ====== 东南亚 (ASEAN) ======
    ("VN", "越南", "Vietnam", "Việt Nam",
     "越南社会主义共和国 卫生部食品安全局", "参照CODEX", "亚洲", "ASEAN成员"),
    ("TH", "泰国", "Thailand", "ประเทศไทย",
     "泰王国 食品药品监督管理局（FDA Thailand）", "自有", "亚洲", "ASEAN成员"),
    ("KH", "柬埔寨", "Cambodia", "កម្ពុជា",
     "柬埔寨王国 工业与手工业部标准局", "参照CODEX", "亚洲", "ASEAN成员"),
    ("LA", "老挝", "Laos", "ລາວ",
     "老挝人民民主共和国 工业与贸易部标准计量司", "参照CODEX", "亚洲", "ASEAN成员"),
    ("MM", "缅甸", "Myanmar", "မြန်မာ",
     "缅甸联邦共和国 食品药品监督管理局（FDA Myanmar）", "参照CODEX", "亚洲", "ASEAN成员"),
    ("MY", "马来西亚", "Malaysia", "Malaysia",
     "马来西亚 卫生部食品安全与质量司", "自有", "亚洲", "ASEAN成员"),
    ("SG", "新加坡", "Singapore", "Singapore",
     "新加坡共和国 食品局（SFA）", "自有", "亚洲", "ASEAN成员"),
    ("ID", "印度尼西亚", "Indonesia", "Indonesia",
     "印度尼西亚共和国 食品药品监督局（BPOM）", "自有", "亚洲", "ASEAN成员"),
    ("PH", "菲律宾", "Philippines", "Pilipinas",
     "菲律宾共和国 食品药品监督管理局（FDA Philippines）", "自有", "亚洲", "ASEAN成员"),
    ("BN", "文莱", "Brunei", "Brunei",
     "文莱达鲁萨兰国 卫生部", "参照CODEX", "亚洲", "ASEAN成员"),
    ("TL", "东帝汶", "Timor-Leste", "Timor-Leste",
     "东帝汶民主共和国 卫生部", "参照CODEX", "亚洲", "ASEAN观察员"),

    # ====== 南亚 ======
    ("IN", "印度", "India", "भारत",
     "印度共和国 食品安全标准局（FSSAI）", "自有", "亚洲", ""),
    ("PK", "巴基斯坦", "Pakistan", "پاکستان",
     "巴基斯坦伊斯兰共和国 卫生部", "参照CODEX", "亚洲", ""),
    ("BD", "孟加拉国", "Bangladesh", "বাংলাদেশ",
     "孟加拉人民共和国 食品安全局", "参照CODEX", "亚洲", ""),
    ("LK", "斯里兰卡", "Sri Lanka", "ශ්රී ලංකා",
     "斯里兰卡民主社会主义共和国 卫生部", "参照CODEX", "亚洲", ""),
    ("NP", "尼泊尔", "Nepal", "नेपाल",
     "尼泊尔联邦民主共和国 食品技术与质量控制司", "参照CODEX", "亚洲", ""),
    ("BT", "不丹", "Bhutan", "འབྲུག",
     "不丹王国 农业部", "参照CODEX", "亚洲", ""),
    ("MV", "马尔代夫", "Maldives", "ދިވެހި",
     "马尔代夫共和国 食品药品监督管理局", "参照CODEX", "亚洲", ""),
    ("AF", "阿富汗", "Afghanistan", "افغانستان",
     "阿富汗伊斯兰酋长国 公共卫生部", "参照CODEX", "亚洲", ""),

    # ====== 中亚 ======
    ("KZ", "哈萨克斯坦", "Kazakhstan", "Қазақстан",
     "哈萨克斯坦共和国 国家安全与质量委员会", "自有", "亚洲", "EAEU成员"),
    ("UZ", "乌兹别克斯坦", "Uzbekistan", "O'zbekiston",
     "乌兹别克斯坦共和国 卫生部", "参照CODEX", "亚洲", ""),
    ("TM", "土库曼斯坦", "Turkmenistan", "Türkmenistan",
     "土库曼斯坦卫生部", "参照CODEX", "亚洲", ""),
    ("KG", "吉尔吉斯斯坦", "Kyrgyzstan", "Кыргызстан",
     "吉尔吉斯共和国 卫生部", "自有", "亚洲", "EAEU成员"),
    ("TJ", "塔吉克斯坦", "Tajikistan", "Тоҷикистон",
     "塔吉克斯坦共和国 卫生与人口社会保障部", "参照CODEX", "亚洲", ""),

    # ====== 西亚 / 中东 (GCC等) ======
    ("SA", "沙特阿拉伯", "Saudi Arabia", "السعودية",
     "沙特阿拉伯王国 食品药品监督管理局（SFDA）", "自有", "亚洲", "GCC成员"),
    ("AE", "阿拉伯联合酋长国", "United Arab Emirates", "الإمارات",
     "阿联酋 阿布扎比农业与食品安全局/联邦海关", "自有", "亚洲", "GCC成员"),
    ("YE", "也门", "Yemen", "اليمن",
     "也门共和国 卫生部", "参照CODEX", "亚洲", "GCC成员"),
    ("OM", "阿曼", "Oman", "عُمان",
     "阿曼苏丹国 市政与水资源部", "自有", "亚洲", "GCC成员"),
    ("KW", "科威特", "Kuwait", "الكويت",
     "科威特国 公共卫生部", "自有", "亚洲", "GCC成员"),
    ("QA", "卡塔尔", "Qatar", "قطر",
     "卡塔尔国 卫生部", "自有", "亚洲", "GCC成员"),
    ("BH", "巴林", "Bahrain", "البحرين",
     "巴林王国 国家卫生监管局", "自有", "亚洲", "GCC成员"),
    ("IQ", "伊拉克", "Iraq", "العراق",
     "伊拉克共和国 标准与质量控制组织", "参照CODEX", "亚洲", ""),
    ("IR", "伊朗", "Iran", "ایران",
     "伊朗伊斯兰共和国 国家标准组织（ISIRI）", "自有", "亚洲", ""),
    ("SY", "叙利亚", "Syria", "سوريا",
     "叙利亚阿拉伯共和国 标准与计量组织", "参照CODEX", "亚洲", ""),
    ("JO", "约旦", "Jordan", "الأردن",
     "约旦哈希姆王国 标准与计量组织", "自有", "亚洲", ""),
    ("LB", "黎巴嫩", "Lebanon", "لبنان",
     "黎巴嫩共和国 经济部标准局", "参照CODEX", "亚洲", ""),
    ("IL", "以色列", "Israel", "ישראל",
     "以色列国 卫生部食品安全局", "自有", "亚洲", ""),
    ("PS", "巴勒斯坦", "Palestine", "فلسطين",
     "巴勒斯坦国 卫生部", "参照CODEX", "亚洲", ""),
    ("TR", "土耳其", "Türkiye", "Türkiye",
     "土耳其共和国 农业与林业部", "自有", "亚洲", ""),
    ("AZ", "阿塞拜疆", "Azerbaijan", "Azərbaycan",
     "阿塞拜疆共和国 食品安全局", "自有", "亚洲", ""),
    ("AM", "亚美尼亚", "Armenia", "Հայաստան",
     "亚美尼亚共和国 食品安全 Inspection Body", "自有", "亚洲", "EAEU成员"),
    ("GE", "格鲁吉亚", "Georgia", "საქართველო",
     "格鲁吉亚 国家食品安全局", "自有", "亚洲", ""),

    # ====== 欧盟体系 ======
    ("EU", "欧盟", "European Union", "Europäische Union",
     "欧洲联盟委员会（European Commission）", "EU", "欧洲", "EU法规体系"),
    ("DE", "德国", "Germany", "Deutschland",
     "德意志联邦共和国 联邦食品与农业部（BMEL）", "EU", "欧洲", "EU成员"),
    ("FR", "法国", "France", "France",
     "法兰西共和国 竞争、消费与反欺诈总局（DGCCRF）", "EU", "欧洲", "EU成员"),
    ("IT", "意大利", "Italy", "Italia",
     "意大利共和国 卫生部", "EU", "欧洲", "EU成员"),
    ("ES", "西班牙", "Spain", "España",
     "西班牙王国 食品安全与营养局（AESAN）", "EU", "欧洲", "EU成员"),
    ("PT", "葡萄牙", "Portugal", "Portugal",
     "葡萄牙共和国 食品安全局（ASAE）", "EU", "欧洲", "EU成员"),
    ("NL", "荷兰", "Netherlands", "Nederland",
     "荷兰王国 食品与消费品安全管理局（NVWA）", "EU", "欧洲", "EU成员"),
    ("BE", "比利时", "Belgium", "België",
     "比利时联邦国 联邦食品链安全局（FASFC）", "EU", "欧洲", "EU成员"),
    ("LU", "卢森堡", "Luxembourg", "Lëtzebuerg",
     "卢森堡大公国 卫生部", "EU", "欧洲", "EU成员"),
    ("AT", "奥地利", "Austria", "Österreich",
     "奥地利共和国 卫生部", "EU", "欧洲", "EU成员"),
    ("IE", "爱尔兰", "Ireland", "Éire",
     "爱尔兰 食品安全局（FSAI）", "EU", "欧洲", "EU成员"),
    ("FI", "芬兰", "Finland", "Suomi",
     "芬兰共和国 食品安全局（Ruokavirasto）", "EU", "欧洲", "EU成员"),
    ("DK", "丹麦", "Denmark", "Danmark",
     "丹麦王国 兽医与食品管理局（DVFA）", "EU", "欧洲", "EU成员"),
    ("SE", "瑞典", "Sweden", "Sverige",
     "瑞典王国 国家食品管理局（Livsmedelsverket）", "EU", "欧洲", "EU成员"),
    ("GR", "希腊", "Greece", "Ελλάδα",
     "希腊共和国 食品管理局（EFET）", "EU", "欧洲", "EU成员"),
    ("PL", "波兰", "Poland", "Polska",
     "波兰共和国 国家兽医研究所-国家卫生检验局", "EU", "欧洲", "EU成员"),
    ("CZ", "捷克", "Czechia", "Česko",
     "捷克共和国 农业与食品检验局（SZPI）", "EU", "欧洲", "EU成员"),
    ("HU", "匈牙利", "Hungary", "Magyarország",
     "匈牙利 国家食品链安全局（NÉBIH）", "EU", "欧洲", "EU成员"),
    ("SK", "斯洛伐克", "Slovakia", "Slovensko",
     "斯洛伐克共和国 国家兽医与食品管理局", "EU", "欧洲", "EU成员"),
    ("SI", "斯洛文尼亚", "Slovenia", "Slovenija",
     "斯洛文尼亚共和国 卫生部食品安全局", "EU", "欧洲", "EU成员"),
    ("HR", "克罗地亚", "Croatia", "Hrvatska",
     "克罗地亚共和国 农业部/卫生部", "EU", "欧洲", "EU成员"),
    ("RO", "罗马尼亚", "Romania", "România",
     "罗马尼亚 国家兽医与食品安全局（ANSVSA）", "EU", "欧洲", "EU成员"),
    ("BG", "保加利亚", "Bulgaria", "България",
     "保加利亚共和国 食品安全局（BFSA）", "EU", "欧洲", "EU成员"),
    ("EE", "爱沙尼亚", "Estonia", "Eesti",
     "爱沙尼亚共和国 兽医与食品局", "EU", "欧洲", "EU成员"),
    ("LV", "拉脱维亚", "Latvia", "Latvija",
     "拉脱维亚共和国 食品与兽医局", "EU", "欧洲", "EU成员"),
    ("LT", "立陶宛", "Lithuania", "Lietuva",
     "立陶宛共和国 国立食品与兽医局", "EU", "欧洲", "EU成员"),
    ("MT", "马耳他", "Malta", "Malta",
     "马耳他共和国 环境卫生局", "EU", "欧洲", "EU成员"),
    ("CY", "塞浦路斯", "Cyprus", "Κύπρος",
     "塞浦路斯共和国 卫生部", "EU", "欧洲", "EU成员"),
    ("HR2", "克罗地亚补充", "", "", "", "", "欧洲", ""),  # placeholder removed below

    # ====== 欧洲非EU (EEA/EFTA + 其他) ======
    ("UK", "英国", "United Kingdom", "United Kingdom",
     "大不列颠及北爱尔兰联合王国 食品标准局（FSA）", "自有", "欧洲", "脱欧后自建(原EU)"),
    ("NO", "挪威", "Norway", "Norge",
     "挪威王国 食品安全局（Mattilsynet）", "参照EU", "欧洲", "EEA/EFTA"),
    ("IS", "冰岛", "Iceland", "Ísland",
     "冰岛共和国 食品与兽医局（MAST）", "参照EU", "欧洲", "EEA/EFTA"),
    ("LI", "列支敦士登", "Liechtenstein", "Liechtenstein",
     "列支敦士登公国 食品安全办公室", "参照EU", "欧洲", "EEA/EFTA"),
    ("CH", "瑞士", "Switzerland", "Schweiz",
     "瑞士联邦 食品安全与兽医局（FSVO）", "参照EU", "欧洲", "EFTA非EEA"),
    ("RU", "俄罗斯", "Russia", "Россия",
     "俄罗斯联邦 消费者权益及公民平安保护监督局（Rospotrebnadzor）", "自有", "欧洲", "EAEU核心"),
    ("BY", "白俄罗斯", "Belarus", "Беларусь",
     "白俄罗斯共和国 卫生部", "自有", "欧洲", "EAEU成员"),
    ("UA", "乌克兰", "Ukraine", "Україна",
     "乌克兰 国家消费者权益保护局", "参照EU", "欧洲", ""),
    ("MD", "摩尔多瓦", "Moldova", "Moldova",
     "摩尔多瓦共和国 国家食品安全局", "参照EU", "欧洲", ""),
    ("RS", "塞尔维亚", "Serbia", "Србија",
     "塞尔维亚共和国 农业部兽医局", "参照EU", "欧洲", ""),
    ("MK", "北马其顿", "North Macedonia", "Северна Македонија",
     "北马其顿共和国 食品与兽医局", "参照EU", "欧洲", ""),
    ("AL", "阿尔巴尼亚", "Albania", "Shqipëria",
     "阿尔巴尼亚共和国 国家食品安全局", "参照EU", "欧洲", ""),
    ("BA", "波黑", "Bosnia and Herzegovina", "Bosna i Hercegovina",
     "波斯尼亚和黑塞哥维那 食品安全局", "参照EU", "欧洲", ""),
    ("ME", "黑山", "Montenegro", "Crna Gora",
     "黑山共和国 食品安全与植物卫生局", "参照EU", "欧洲", ""),
    ("XK", "科索沃", "Kosovo", "Kosova",
     "科索沃地区 食品与兽医局", "参照EU", "欧洲", "地区"),

    # ====== 北美 ======
    ("US", "美国", "United States", "United States",
     "美国 食品药品监督管理局（FDA）/ 环境保护署（EPA）", "US", "北美洲", "联邦法规CFR"),
    ("CA", "加拿大", "Canada", "Canada",
     "加拿大卫生部（Health Canada）", "自有", "北美洲", ""),
    ("MX", "墨西哥", "Mexico", "México",
     "墨西哥合众国 联邦卫生风险防护委员会（COFEPRIS）", "自有", "北美洲", ""),

    # ====== 中美洲 ======
    ("GT", "危地马拉", "Guatemala", "Guatemala",
     "危地马拉共和国 卫生部", "参照CODEX", "北美洲", ""),
    ("BZ", "伯利兹", "Belize", "Belize",
     "伯利兹 卫生部", "参照CODEX", "北美洲", ""),
    ("SV", "萨尔瓦多", "El Salvador", "El Salvador",
     "萨尔瓦多共和国 卫生部", "参照CODEX", "北美洲", ""),
    ("HN", "洪都拉斯", "Honduras", "Honduras",
     "洪都拉斯共和国 卫生部", "参照CODEX", "北美洲", ""),
    ("NI", "尼加拉瓜", "Nicaragua", "Nicaragua",
     "尼加拉瓜共和国 卫生部", "参照CODEX", "北美洲", ""),
    ("CR", "哥斯达黎加", "Costa Rica", "Costa Rica",
     "哥斯达黎加共和国 卫生部", "参照CODEX", "北美洲", ""),
    ("PA", "巴拿马", "Panama", "Panamá",
     "巴拿马共和国 食品安全局", "参照CODEX", "北美洲", ""),

    # ====== 加勒比 (CARICOM) ======
    ("CU", "古巴", "Cuba", "Cuba",
     "古巴共和国 卫生部", "参照CODEX", "北美洲", ""),
    ("JM", "牙买加", "Jamaica", "Jamaica",
     "牙买加 标准局（BSJ）", "参照CODEX", "北美洲", "CARICOM成员"),
    ("HT", "海地", "Haiti", "Haïti",
     "海地共和国 卫生部", "参照CODEX", "北美洲", "CARICOM观察员"),
    ("DO", "多米尼加", "Dominican Republic", "República Dominicana",
     "多米尼加共和国 卫生部", "参照CODEX", "北美洲", ""),
    ("BS", "巴哈马", "Bahamas", "Bahamas",
     "巴哈马国 卫生部", "参照CODEX", "北美洲", "CARICOM成员"),
    ("TT", "特立尼达和多巴哥", "Trinidad and Tobago", "Trinidad y Tobago",
     "特立尼达和多巴哥共和国 化学食品与药物司", "参照CODEX", "北美洲", "CARICOM成员"),
    ("BB", "巴巴多斯", "Barbados", "Barbados",
     "巴巴多斯 卫生部", "参照CODEX", "北美洲", "CARICOM成员"),
    ("GD", "格林纳达", "Grenada", "Grenada",
     "格林达 卫生部", "参照CODEX", "北美洲", "CARICOM成员"),
    ("LC", "圣卢西亚", "Saint Lucia", "Saint Lucia",
     "圣卢西亚 卫生部", "参照CODEX", "北美洲", "CARICOM成员"),
    ("VC", "圣文森特", "Saint Vincent and the Grenadines", "Saint Vincent",
     "圣文森特和格林纳丁斯 卫生部", "参照CODEX", "北美洲", "CARICOM成员"),
    ("AG", "安提瓜和巴布达", "Antigua and Barbuda", "Antigua",
     "安提瓜和巴布达 卫生部", "参照CODEX", "北美洲", "CARICOM成员"),
    ("DM", "多米尼克", "Dominica", "Dominica",
     "多米尼克国 卫生部", "参照CODEX", "北美洲", "CARICOM成员"),
    ("KN", "圣基茨和尼维斯", "Saint Kitts and Nevis", "Saint Kitts",
     "圣基茨和尼维斯联邦 卫生部", "参照CODEX", "北美洲", "CARICOM成员"),

    # ====== 南美 (MERCOSUR等) ======
    ("BR", "巴西", "Brazil", "Brasil",
     "巴西联邦共和国 国家卫生监督局（ANVISA）", "自有", "南美洲", "MERCOSUR成员"),
    ("AR", "阿根廷", "Argentina", "Argentina",
     "阿根廷共和国 国家食品委员会（CONAL）", "自有", "南美洲", "MERCOSUR成员"),
    ("CL", "智利", "Chile", "Chile",
     "智利共和国 农业部农牧局（SAG）/卫生部", "自有", "南美洲", ""),
    ("CO", "哥伦比亚", "Colombia", "Colombia",
     "哥伦比亚共和国 国家食品药品监管局（INVIMA）", "自有", "南美洲", ""),
    ("PE", "秘鲁", "Peru", "Perú",
     "秘鲁共和国 国家农业卫生局（SENASA）", "自有", "南美洲", ""),
    ("VE", "委内瑞拉", "Venezuela", "Venezuela",
     "委内瑞拉玻利瓦尔共和国 卫生部", "参照CODEX", "南美洲", "MERCOSUR成员"),
    ("EC", "厄瓜多尔", "Ecuador", "Ecuador",
     "厄瓜多尔共和国 卫生部/农业质量局", "参照CODEX", "南美洲", ""),
    ("BO", "玻利维亚", "Bolivia", "Bolivia",
     "玻利维亚多民族国 国家农业健康与食品安全局（SENASAG）", "参照CODEX", "南美洲", "MERCOSUR成员"),
    ("PY", "巴拉圭", "Paraguay", "Paraguay",
     "巴拉圭共和国 国家植物与种子质量与卫生局（SEAVE）", "参照CODEX", "南美洲", "MERCOSUR成员"),
    ("UY", "乌拉圭", "Uruguay", "Uruguay",
     "乌拉圭东岸共和国 国家牛奶质量与生产局（MGAP）", "自有", "南美洲", "MERCOSUR成员"),
    ("GY", "圭亚那", "Guyana", "Guyana",
     "圭亚那合作共和国 农业部", "参照CODEX", "南美洲", "CARICOM成员"),
    ("SR", "苏里南", "Suriname", "Suriname",
     "苏里南共和国 卫生部", "参照CODEX", "南美洲", "CARICOM成员"),

    # ====== 大洋洲 (SPC/PIF) ======
    ("AU/NZ", "澳大利亚/新西兰", "Australia/New Zealand", "Australia/New Zealand",
     "澳大利亚/新西兰食品标准局（FSANZ）", "自有", "大洋洲", "澳新联合标准"),
    ("FJ", "斐济", "Fiji", "Fiji",
     "斐济共和国 卫生部", "参照CODEX", "大洋洲", "PIF成员"),
    ("PG", "巴布亚新几内亚", "Papua New Guinea", "Papua Niugini",
     "巴布亚新几内亚独立国 卫生部", "参照CODEX", "大洋洲", "PIF成员"),
    ("SB", "所罗门群岛", "Solomon Islands", "Solomon Islands",
     "所罗门群岛 卫生部", "参照CODEX", "大洋洲", "PIF成员"),
    ("VU", "瓦努阿图", "Vanuatu", "Vanuatu",
     "瓦努阿图共和国 卫生部", "参照CODEX", "大洋洲", "PIF成员"),
    ("WS", "萨摩亚", "Samoa", "Sāmoa",
     "萨摩亚独立国 卫生部", "参照CODEX", "大洋洲", "PIF成员"),
    ("TO", "汤加", "Tonga", "Tonga",
     "汤加王国 卫生部", "参照CODEX", "大洋洲", "PIF成员"),
    ("KI", "基里巴斯", "Kiribati", "Kiribati",
     "基里巴斯共和国 卫生部", "参照CODEX", "大洋洲", "PIF成员"),
    ("TV", "图瓦卢", "Tuvalu", "Tuvalu",
     "图瓦卢 卫生部", "参照CODEX", "大洋洲", "PIF成员"),
    ("NR", "瑙鲁", "Nauru", "Nauru",
     "瑙鲁共和国 卫生部", "参照CODEX", "大洋洲", "PIF成员"),
    ("PW", "帕劳", "Palau", "Palau",
     "帕劳共和国 卫生部", "参照CODEX", "大洋洲", "PIF成员"),
    ("MH", "马绍尔群岛", "Marshall Islands", "Marshall Islands",
     "马绍尔群岛共和国 卫生部", "参照CODEX", "大洋洲", "PIF成员"),
    ("FM", "密克罗尼西亚", "Micronesia", "Micronesia",
     "密克罗尼西亚联邦 卫生部", "参照CODEX", "大洋洲", "PIF成员"),
    ("CK", "库克群岛", "Cook Islands", "Cook Islands",
     "库克群岛 卫生部", "参照CODEX", "大洋洲", "PIF成员"),
    ("NU", "纽埃", "Niue", "Niue",
     "纽埃 卫生部", "参照CODEX", "大洋洲", "PIF成员"),

    # ====== 北非 ======
    ("EG", "埃及", "Egypt", "مصر",
     "埃及共和国 食品安全局（NFA）", "自有", "非洲", ""),
    ("LY", "利比亚", "Libya", "ليبيا",
     "利比亚国 卫生部", "参照CODEX", "非洲", ""),
    ("TN", "突尼斯", "Tunisia", "تونس",
     "突尼斯共和国 消费者保护与欺诈制止局", "自有", "非洲", ""),
    ("DZ", "阿尔及利亚", "Algeria", "الجزائر",
     "阿尔及利亚民主人民共和国 商业部", "自有", "非洲", ""),
    ("MA", "摩洛哥", "Morocco", "المغرب",
     "摩洛哥王国 国家食品安全局（ONSSA）", "自有", "非洲", ""),
    ("SD", "苏丹", "Sudan", "السودان",
     "苏丹共和国 卫生部", "参照CODEX", "非洲", ""),
    ("SS", "南苏丹", "South Sudan", "South Sudan",
     "南苏丹共和国 卫生部", "参照CODEX", "非洲", ""),

    # ====== 东非 (EAC) ======
    ("ET", "埃塞俄比亚", "Ethiopia", "ኢትዮጵያ",
     "埃塞俄比亚联邦民主共和国 食品与药品监管局", "参照CODEX", "非洲", ""),
    ("ER", "厄立特里亚", "Eritrea", "ኤርትራ",
     "厄立特里亚国 卫生部", "参照CODEX", "非洲", ""),
    ("DJ", "吉布提", "Djibouti", "جيبوتي",
     "吉布提共和国 卫生部", "参照CODEX", "非洲", ""),
    ("SO", "索马里", "Somalia", "Soomaaliya",
     "索马里联邦共和国 卫生部", "参照CODEX", "非洲", ""),
    ("KE", "肯尼亚", "Kenya", "Kenya",
     "肯尼亚共和国 食品安全局（KEBS）", "自有", "非洲", "EAC成员"),
    ("UG", "乌干达", "Uganda", "Uganda",
     "乌干达共和国 国家标准局（UNBS）", "自有", "非洲", "EAC成员"),
    ("TZ", "坦桑尼亚", "Tanzania", "Tanzania",
     "坦桑尼亚联合共和国 坦桑尼亚标准局（TBS）", "自有", "非洲", "EAC成员"),
    ("RW", "卢旺达", "Rwanda", "Rwanda",
     "卢旺达共和国 卢旺达标准局（RSB）", "自有", "非洲", "EAC成员"),
    ("BI", "布隆迪", "Burundi", "Burundi",
     "布隆迪共和国 标准与质量控制局（BBN）", "参照CODEX", "非洲", "EAC成员"),
    ("MZ", "莫桑比克", "Mozambique", "Moçambique",
     "莫桑比克共和国 国家卫生研究所", "参照CODEX", "非洲", ""),
    ("MW", "马拉维", "Malawi", "Malawi",
     "马拉维共和国 马拉维标准局（MBS）", "参照CODEX", "非洲", ""),
    ("ZM", "赞比亚", "Zambia", "Zambia",
     "赞比亚共和国 赞比亚标准局（ZABS）", "参照CODEX", "非洲", ""),
    ("ZW", "津巴布韦", "Zimbabwe", "Zimbabwe",
     "津巴布韦共和国 标准协会（SAZ）", "参照CODEX", "非洲", ""),
    ("BW", "博茨瓦纳", "Botswana", "Botswana",
     "博茨瓦纳共和国 博茨瓦纳标准局（BOBS）", "参照CODEX", "非洲", "SADC成员"),
    ("NA", "纳米比亚", "Namibia", "Namibia",
     "纳米比亚共和国 标准局（NSI）", "参照CODEX", "非洲", "SADC成员"),
    ("ZA", "南非", "South Africa", "South Africa",
     "南非共和国 卫生部食品安全司", "自有", "非洲", "SADC成员"),
    ("LS", "莱索托", "Lesotho", "Lesotho",
     "莱索托王国 标准局（LSQAS）", "参照CODEX", "非洲", "SADC成员"),
    ("SZ", "斯威士兰", "Eswatini", "eSwatini",
     "斯威士兰王国 卫生部", "参照CODEX", "非洲", "SADC成员"),
    ("AO", "安哥拉", "Angola", "Angola",
     "安哥拉共和国 经济部标准与质量局", "参照CODEX", "非洲", "SADC成员"),
    ("MG", "马达加斯加", "Madagascar", "Madagasikara",
     "马达加斯加共和国 标准局", "参照CODEX", "非洲", "SADC成员"),
    ("MU", "毛里求斯", "Mauritius", "Maurice",
     "毛里求斯共和国 卫生部", "自有", "非洲", "SADC成员"),
    ("SC", "塞舌尔", "Seychelles", "Seychelles",
     "塞舌尔共和国 卫生部", "参照CODEX", "非洲", "SADC成员"),
    ("KM", "科摩罗", "Comoros", "Komori",
     "科摩罗联盟 卫生部", "参照CODEX", "非洲", ""),

    # ====== 中非 (ECCAS) ======
    ("CG", "刚果(布)", "Congo", "Congo",
     "刚果共和国 卫生部", "参照CODEX", "非洲", "ECCAS成员"),
    ("CD", "刚果(金)", "DR Congo", "RD Congo",
     "刚果民主共和国 国家食品安全局", "参照CODEX", "非洲", "ECCAS成员"),
    ("GA", "加蓬", "Gabon", "Gabon",
     "加蓬共和国 卫生部", "参照CODEX", "非洲", "ECCAS成员"),
    ("GQ", "赤道几内亚", "Equatorial Guinea", "Guinea Ecuatorial",
     "赤道几内亚共和国 卫生部", "参照CODEX", "非洲", "ECCAS成员"),
    ("ST", "圣多美和普林西比", "São Tomé and Príncipe", "São Tomé",
     "圣多美和普林西比民主共和国 卫生部", "参照CODEX", "非洲", "ECCAS成员"),
    ("CM", "喀麦隆", "Cameroon", "Cameroun",
     "喀麦隆共和国 标准与质量局（ANOR）", "参照CODEX", "非洲", "ECCAS成员"),
    ("TD", "乍得", "Chad", "Tchad",
     "乍得共和国 卫生部", "参照CODEX", "非洲", "ECCAS成员"),
    ("CF", "中非", "Central African Republic", "Centrafrique",
     "中非共和国 卫生部", "参照CODEX", "非洲", "ECCAS成员"),
    ("CG2", "刚果补充", "", "", "", "", "非洲", ""),  # placeholder

    # ====== 西非 (ECOWAS) ======
    ("NG", "尼日利亚", "Nigeria", "Nigeria",
     "尼日利亚联邦共和国 国家食品药品管理控制局（NAFDAC）", "自有", "非洲", "ECOWAS成员"),
    ("BJ", "贝宁", "Benin", "Bénin",
     "贝宁共和国 卫生部", "参照CODEX", "非洲", "ECOWAS成员"),
    ("CI", "科特迪瓦", "Côte d'Ivoire", "Côte d'Ivoire",
     "科特迪瓦共和国 卫生部", "参照CODEX", "非洲", "ECOWAS成员"),
    ("GH", "加纳", "Ghana", "Ghana",
     "加纳共和国 食品与药品管理局（FDA Ghana）", "自有", "非洲", "ECOWAS成员"),
    ("TG", "多哥", "Togo", "Togo",
     "多哥共和国 卫生部", "参照CODEX", "非洲", "ECOWAS成员"),
    ("BF", "布基纳法索", "Burkina Faso", "Burkina Faso",
     "布基纳法索 卫生部", "参照CODEX", "非洲", "ECOWAS成员"),
    ("ML", "马里", "Mali", "Mali",
     "马里共和国 国家卫生实验室", "参照CODEX", "非洲", "ECOWAS成员"),
    ("SN", "塞内加尔", "Senegal", "Sénégal",
     "塞内加尔共和国 卫生部", "参照CODEX", "非洲", "ECOWAS成员"),
    ("GM", "冈比亚", "Gambia", "Gambia",
     "冈比亚共和国 卫生部", "参照CODEX", "非洲", "ECOWAS成员"),
    ("GW", "几内亚比绍", "Guinea-Bissau", "Guiné-Bissau",
     "几内亚比绍共和国 卫生部", "参照CODEX", "非洲", "ECOWAS成员"),
    ("CV", "佛得角", "Cape Verde", "Cabo Verde",
     "佛得角共和国 卫生部", "参照CODEX", "非洲", "ECOWAS成员"),
    ("SL", "塞拉利昂", "Sierra Leone", "Sierra Leone",
     "塞拉利昂共和国 卫生部", "参照CODEX", "非洲", "ECOWAS成员"),
    ("LR", "利比里亚", "Liberia", "Liberia",
     "利比里亚共和国 卫生部", "参照CODEX", "非洲", "ECOWAS成员"),
    ("MR", "毛里塔尼亚", "Mauritania", "موريتانيا",
     "毛里塔尼亚伊斯兰共和国 卫生部", "参照CODEX", "非洲", ""),
    ("NE", "尼日尔", "Niger", "Niger",
     "尼日尔共和国 卫生部", "参照CODEX", "非洲", "ECOWAS成员"),
    ("SH", "圣赫勒拿", "Saint Helena", "Saint Helena",
     "圣赫勒拿 卫生局", "参照EU", "非洲", "英国海外领地"),
    ("EH", "西撒哈拉", "Western Sahara", "الصحراء الغربية",
     "西撒哈拉地区 卫生部门", "参照CODEX", "非洲", "争议地区"),

    # ====== 区域性组织/联盟 ======
    ("ASEAN", "东南亚国家联盟", "ASEAN", "ASEAN",
     "东南亚国家联盟（ASEAN）标准与质量咨询委员会", "国际", "国际", "区域协调框架"),
    ("GCC", "海湾合作委员会", "GCC", "GCC",
     "海湾合作委员会标准化组织（GSO）", "国际", "国际", "区域协调框架"),
    ("EAEU", "欧亚经济联盟", "EAEU", "ЕАЭС",
     "欧亚经济联盟 食品安全技术法规", "国际", "国际", "区域协调框架"),
    ("MERCOSUR", "南方共同市场", "MERCOSUR", "MERCOSUR",
     "南方共同市场（MERCOSUR）食品委员会", "国际", "国际", "区域协调框架"),
    ("CARICOM", "加勒比共同体", "CARICOM", "CARICOM",
     "加勒比共同体（CARICOM）区域标准与质量组织（CROSQ）", "国际", "国际", "区域协调框架"),
    ("EAC", "东非共同体", "EAC", "EAC",
     "东非共同体（EAC）标准与质量委员会", "国际", "国际", "区域协调框架"),
    ("ECOWAS", "西非国家经济共同体", "ECOWAS", "ECOWAS",
     "西非国家经济共同体（ECOWAS）", "国际", "国际", "区域协调框架"),
    ("SADC", "南部非洲发展共同体", "SADC", "SADC",
     "南部非洲发展共同体（SADC）", "国际", "国际", "区域协调框架"),
    ("ECCAS", "中部非洲国家经济共同体", "ECCAS", "ECCAS",
     "中部非洲国家经济共同体（ECCAS）", "国际", "国际", "区域协调框架"),
    ("SPC/PIF", "太平洋共同体/论坛", "Pacific Community/Forum", "Pacific",
     "太平洋共同体（SPC）/ 太平洋岛国论坛（PIF）", "国际", "国际", "区域协调框架"),
    ("APEC", "亚太经济合作组织", "APEC", "APEC",
     "亚太经济合作组织（APEC）食品安全合作论坛", "国际", "国际", "区域协调框架"),
    ("COMESA", "东南非共同市场", "COMESA", "COMESA",
     "东南非共同市场（COMESA）", "国际", "国际", "区域协调框架"),
    ("CABEI", "中美洲一体化体系", "SICA", "SICA",
     "中美洲一体化体系（SICA）", "国际", "国际", "区域协调框架"),

    # ====== 欧洲微型国家(补充) ======
    ("SM", "圣马力诺", "San Marino", "San Marino",
     "圣马力诺共和国 卫生部", "参照EU", "欧洲", ""),
    ("MC", "摩纳哥", "Monaco", "Monaco",
     "摩纳哥公国 卫生与社会事务部", "参照EU", "欧洲", ""),
    ("AD", "安道尔", "Andorra", "Andorra",
     "安道尔公国 卫生部", "参照EU", "欧洲", ""),
    ("VA", "梵蒂冈", "Vatican City", "Città del Vaticano",
     "梵蒂冈城国 卫生服务处", "参照EU", "欧洲", ""),

    # ====== 海外领地/特别地区(补充) ======
    ("GL", "格陵兰", "Greenland", "Kalaallit Nunaat",
     "格陵兰自治体 卫生部", "参照EU", "欧洲", "丹麦自治领地"),
    ("PR", "波多黎各", "Puerto Rico", "Puerto Rico",
     "波多黎各 卫生部", "US", "北美洲", "美国未合并领地"),
    ("GP", "瓜德罗普", "Guadeloupe", "Guadeloupe",
     "瓜德罗普 卫生局", "EU", "北美洲", "法国海外省"),
    ("MQ", "马提尼克", "Martinique", "Martinique",
     "马提尼克 卫生局", "EU", "北美洲", "法国海外省"),
    ("GF", "法属圭亚那", "French Guiana", "Guyane",
     "法属圭亚那 卫生局", "EU", "南美洲", "法国海外省"),
    ("RE", "留尼汪", "Réunion", "La Réunion",
     "留尼汪省 卫生局", "EU", "非洲", "法国海外省"),
    ("YT", "马约特", "Mayotte", "Mayotte",
     "马约特省 卫生局", "EU", "非洲", "法国海外省"),
    ("BQ", "博奈尔", "Bonaire", "Bonaire",
     "博奈尔 公共卫生部", "参照EU", "北美洲", "荷兰特别市镇"),
    ("CW", "库拉索", "Curaçao", "Curaçao",
     "库拉索 卫生部", "参照EU", "北美洲", "荷兰自治国"),
    ("SX", "圣马丁(荷)", "Sint Maarten", "Sint Maarten",
     "圣马丁 卫生部", "参照EU", "北美洲", "荷兰自治国"),
    ("NC", "新喀里多尼亚", "New Caledonia", "Nouvelle-Calédonie",
     "新喀里多尼亚 卫生与社会事务局", "参照EU", "大洋洲", "法国海外领地"),
    ("PF", "法属波利尼西亚", "French Polynesia", "Polynésie française",
     "法属波利尼西亚 卫生部", "参照EU", "大洋洲", "法国海外领地"),
]

# 过滤占位行
REGIONS_DATA = [r for r in REGIONS_DATA if r[1] and r[2]]

# 派生字典：方便 build_xlsx.py 使用
REGION_INFO = {r[0]: (r[1], r[2], r[3]) for r in REGIONS_DATA}      # code -> (zh, en, native)
REGION_FULLNAME = {r[0]: r[4] for r in REGIONS_DATA}                # code -> 主管机构全称
REGION_SYSTEM = {r[0]: r[5] for r in REGIONS_DATA}                   # code -> 适用标准体系
REGION_CONTINENT = {r[0]: r[6] for r in REGIONS_DATA}               # code -> 洲
REGION_NOTE = {r[0]: r[7] for r in REGIONS_DATA}                    # code -> 备注
ALL_REGIONS = [r[0] for r in REGIONS_DATA]                           # 全量地区代码列表(有序)

# 按洲分组（用于 Sheet4 矩阵分区）
CONTINENT_ORDER = ["国际", "亚洲", "欧洲", "北美洲", "南美洲", "大洋洲", "非洲"]
REGIONS_BY_CONTINENT = {}
for r in REGIONS_DATA:
    cont = r[6]
    REGIONS_BY_CONTINENT.setdefault(cont, []).append(r[0])

def region_count():
    return len(ALL_REGIONS)

if __name__ == "__main__":
    print(f"全量地区数: {region_count()}")
    for cont in CONTINENT_ORDER:
        codes = REGIONS_BY_CONTINENT.get(cont, [])
        print(f"  {cont}: {len(codes)} 个 — {codes[:8]}{'...' if len(codes)>8 else ''}")
